# Generated by Django 4.0.5 on 2022-06-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
