# Generated by Django 4.0.5 on 2022-06-21 15:31

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('telesearch', '0003_product_orginal_price'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='telesearch__name_d2b8d2_gin'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'username'], name='telesearch__name_66c643_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description', 'category', 'channel'], name='telesearch__title_53e532_gin'),
        ),
    ]
