# Generated by Django 4.0.5 on 2022-06-21 15:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesearch', '0004_category_telesearch__name_d2b8d2_gin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='telesearch__name_d2b8d2_gin',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='telesearch__name_66c643_gin',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='telesearch__title_53e532_gin',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='NewGinIndex', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
