# Generated by Django 4.0.5 on 2022-06-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesearch', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='NewGinIndex',
        ),
    ]
