# Generated by Django 4.0.5 on 2022-06-21 15:44

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesearch', '0006_remove_product_newginindex'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='NewGinIndex', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
