# Generated by Django 4.0.5 on 2022-06-21 15:46

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesearch', '0007_product_newginindex'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='NewCatnGinIndex', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'description'], name='NewChanGinIndex', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
