# Generated by Django 4.0.5 on 2022-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesearch', '0008_category_newcatnginindex_channel_newchanginindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related_name',
            field=models.TextField(blank=True, null=True, verbose_name='Related Name'),
        ),
    ]
