# Generated by Django 4.0.5 on 2022-06-21 16:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesearch', '0009_category_related_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='NewCatnGinIndex',
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'related_name'], name='NewCatnGinIndex', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
