# Generated by Django 4.0.5 on 2022-06-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesearch', '0011_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.FileField(default=None, upload_to='images/product'),
        ),
    ]
