# Generated by Django 4.0.5 on 2022-06-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesearch', '0014_alter_product_image_alter_productimages_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
